# Generated by Django 4.2.23 on 2025-08-13 12:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sorteo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Titulo")),
                ("slug", models.SlugField(editable=False, max_length=110, unique=True)),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "date_lottery",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha del Sorteo"
                    ),
                ),
                (
                    "date_lottery_text",
                    models.CharField(
                        blank=True,
                        help_text="Ej: 'Al alcanzar el 80% de los tickets vendidos'. Usar si no se define una fecha específica.",
                        max_length=150,
                        null=True,
                        verbose_name="Texto alternativo para la fecha",
                    ),
                ),
                (
                    "prize_picture",
                    models.ImageField(
                        upload_to="premios/", verbose_name="Foto del premio"
                    ),
                ),
                (
                    "ticket_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Precio del ticket"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("B", "BORRADOR"),
                            ("A", "ACTIVO"),
                            ("F", "FINALIZADO"),
                            ("V", "VENDIDO"),
                        ],
                        default="B",
                        max_length=150,
                        verbose_name="Estado del sorteo",
                    ),
                ),
                (
                    "total_tickets",
                    models.PositiveIntegerField(
                        verbose_name="Máxima cantidad de tickets a vender"
                    ),
                ),
                (
                    "tickets_solds",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Tickets vendidos"
                    ),
                ),
                (
                    "lottery_conditions",
                    models.TextField(verbose_name="Condiciones del sorteo"),
                ),
                (
                    "minimun_tickets_buy",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Cantidad mínima de tickets a  comprar",
                    ),
                ),
                (
                    "video_promo",
                    models.FileField(
                        blank=True,
                        help_text="Sube un video promocional del sorteo",
                        null=True,
                        upload_to="premios/",
                        verbose_name="Video promocional",
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False,
                        help_text="Marcar si este es el sorteo principal que se mostrará en la página de inicio. Solo uno puede ser principal.",
                        verbose_name="Sorteo Principal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sorteo",
                "verbose_name_plural": "Sorteos",
            },
        ),
        migrations.CreateModel(
            name="Premio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nombre del premio"),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Descripción del premio"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        help_text="El orden en que se mostrará el premio (1, 2, 3...)",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "sorteo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premios",
                        to="sorteo.sorteo",
                        verbose_name="Sorteo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Premio",
                "verbose_name_plural": "Premios",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        max_length=50, verbose_name="Nombre del propietario"
                    ),
                ),
                (
                    "owner_ci",
                    models.CharField(
                        max_length=8,
                        validators=[django.core.validators.MinLengthValidator(6)],
                        verbose_name="Cedula del propietario",
                    ),
                ),
                (
                    "owner_email",
                    models.EmailField(
                        max_length=254, verbose_name="Correo del propietario"
                    ),
                ),
                (
                    "owner_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128,
                        region="VE",
                        verbose_name="Telefono del propietario",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("P", "Pago Móvil"),
                            ("Z", "Zelle"),
                            ("E", "Efectivo"),
                        ],
                        max_length=50,
                        verbose_name="Método de Pago",
                    ),
                ),
                (
                    "reference",
                    models.CharField(max_length=30, verbose_name="Referencia"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("V", "Verificado"),
                            ("E", "En Espera"),
                            ("C", "Cancelado"),
                        ],
                        max_length=50,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="Ultima actualización"
                    ),
                ),
                ("tickets_quantity", models.PositiveBigIntegerField()),
                (
                    "serial",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=50,
                        verbose_name="Serial de la transacción",
                    ),
                ),
                (
                    "transferred_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Monto transferido",
                    ),
                ),
                (
                    "transferred_date",
                    models.DateField(verbose_name="Fecha de transferencia"),
                ),
                (
                    "type_CI",
                    models.CharField(
                        choices=[
                            ("V", "Venezolano"),
                            ("E", "Extranjero"),
                            ("J", "Jurídico"),
                        ],
                        default="V",
                        max_length=1,
                        verbose_name="Tipo de cédula",
                    ),
                ),
                (
                    "bank_of_transfer",
                    models.CharField(
                        choices=[
                            ("0102", "Banco de Venezuela"),
                            ("0104", "Banco Venezolano de Crédito"),
                            ("0105", "Banco Mercantil"),
                            ("0108", "Banco Provincial"),
                            ("0114", "Bancaribe"),
                            ("0115", "Banco Exterior"),
                            ("0128", "Banco Caroní"),
                            ("0134", "Banesco"),
                            ("0137", "Banco Sofitasa"),
                            ("0138", "Banco Plaza"),
                            ("0151", "BFC Banco Fondo Común"),
                            ("0156", "100% Banco"),
                            ("0157", "DelSur Banco Universal"),
                            ("0163", "Banco del Tesoro"),
                            ("0166", "Banco Agrícola de Venezuela"),
                            ("0168", "Bancrecer"),
                            ("0169", "Mi Banco"),
                            ("0171", "Banco Activo"),
                            ("0172", "Bancamiga"),
                            ("0174", "Banplus"),
                            ("0175", "Banco Bicentenario del Pueblo"),
                            ("0177", "Banfanb"),
                            ("0191", "BNC Banco Nacional de Crédito"),
                        ],
                        max_length=4,
                        verbose_name="Banco de transferencia",
                    ),
                ),
                (
                    "sorteo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="sorteo.sorteo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial",
                    models.PositiveIntegerField(verbose_name="Número de ticket"),
                ),
                (
                    "owner_name",
                    models.CharField(
                        max_length=50, verbose_name="Nombre del propietario"
                    ),
                ),
                (
                    "owner_ci",
                    models.CharField(
                        max_length=8,
                        validators=[django.core.validators.MinLengthValidator(6)],
                        verbose_name="Cedula del propietario",
                    ),
                ),
                (
                    "owner_email",
                    models.EmailField(
                        max_length=254, verbose_name="Correo del propietario"
                    ),
                ),
                (
                    "owner_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128,
                        region="VE",
                        verbose_name="Telefono del propietario",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="sorteo.payment",
                        verbose_name="Pago",
                    ),
                ),
                (
                    "sorteo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="sorteo.sorteo",
                        verbose_name="Sorteo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
                "unique_together": {("serial", "sorteo")},
            },
        ),
    ]
