# Generated by Django 5.2.4 on 2025-08-08 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_payment_registered',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_verification_note',
        ),
        migrations.AddField(
            model_name='sorteo',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Marcar si este es el sorteo principal que se mostrará en la página de inicio. Solo uno puede ser principal.', verbose_name='Sorteo Principal'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('P', 'Pago Móvil'), ('Z', 'Zelle'), ('E', 'Efectivo')], max_length=50, verbose_name='Método de Pago'),
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del premio')),
                ('description', models.TextField(verbose_name='Descripción del premio')),
                ('position', models.PositiveIntegerField(help_text='El orden en que se mostrará el premio (1, 2, 3...)', verbose_name='Orden')),
                ('image', models.ImageField(blank=True, null=True, upload_to='premios_fotos/', verbose_name='Foto del premio')),
                ('sorteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios', to='sorteo.sorteo', verbose_name='Sorteo')),
            ],
            options={
                'verbose_name': 'Premio',
                'verbose_name_plural': 'Premios',
                'ordering': ['position'],
            },
        ),
    ]
