# Generated by Django 5.2.4 on 2025-08-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0002_remove_payment_is_payment_registered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premio',
            name='image',
        ),
        migrations.AddField(
            model_name='sorteo',
            name='date_lottery_text',
            field=models.CharField(blank=True, help_text="Ej: 'Al alcanzar el 80% de los tickets vendidos'. Usar si no se define una fecha específica.", max_length=150, null=True, verbose_name='Texto alternativo para la fecha'),
        ),
        migrations.AlterField(
            model_name='sorteo',
            name='date_lottery',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha del Sorteo'),
        ),
    ]
