# Generated by Django 5.2.4 on 2025-08-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0003_remove_premio_image_sorteo_date_lottery_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteo',
            name='minimun_tickets_buy',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad mínima de tickets a  comprar'),
        ),
        migrations.AlterField(
            model_name='sorteo',
            name='video_promo',
            field=models.FileField(blank=True, help_text='Sube un video promocional del sorteo', null=True, upload_to='premios/', verbose_name='Video promocional'),
        ),
    ]
